# -*- coding: utf-8 -*-
"""
Verdict consistency contract: NEXT_REAL_ITERATION_ALLOWED must be consistent with CONTINUOUS_CLEANUP_START_VERDICT.
Forbidden: CONTINUOUS = NOT READY and NEXT = YES.
"""
from __future__ import annotations

VERDICT_CONSISTENCY_CONTRACT = [
    "A) If CONTINUOUS_CLEANUP_START_VERDICT = NOT READY TO CONTINUE CLEANUP LOOP then NEXT_REAL_ITERATION_ALLOWED = NO.",
    "B) NEXT_REAL_ITERATION_ALLOWED = YES is allowed only if both: EVIDENCE_PERSISTENCE_VERDICT = PASS and CONTINUOUS_CLEANUP_START_VERDICT = READY FOR CONTINUOUS GUARDED CLEANUP LOOP.",
]

ALLOWED_COMBINATIONS = [
    "CONTINUOUS = READY FOR CONTINUOUS GUARDED CLEANUP LOOP, EVIDENCE_PERSISTENCE = PASS, NEXT = YES",
    "CONTINUOUS = NOT READY TO CONTINUE CLEANUP LOOP, EVIDENCE_PERSISTENCE = PASS or FAIL, NEXT = NO",
]

FORBIDDEN_COMBINATIONS = [
    "CONTINUOUS = NOT READY TO CONTINUE CLEANUP LOOP and NEXT_REAL_ITERATION_ALLOWED = YES",
    "NEXT = YES without EVIDENCE_PERSISTENCE_VERDICT = PASS",
]

EMITTER_RULE_AFTER_FIX = (
    "Compute NEXT_REAL_ITERATION_ALLOWED from CONTINUOUS_CLEANUP_START_VERDICT and EVIDENCE_PERSISTENCE_VERDICT: "
    "NEXT = YES only when CONTINUOUS = READY FOR CONTINUOUS GUARDED CLEANUP LOOP and EVIDENCE_PERSISTENCE = PASS; "
    "otherwise NEXT = NO."
)


def next_real_iteration_allowed(continuous_verdict: str, evidence_persistence_verdict: str) -> bool:
    """Returns True only if CONTINUOUS is READY and EVIDENCE_PERSISTENCE is PASS."""
    ready = continuous_verdict == "READY FOR CONTINUOUS GUARDED CLEANUP LOOP"
    evidence_ok = evidence_persistence_verdict == "PASS"
    return bool(ready and evidence_ok)
