/**
 * Public section titles — synced from assets/iu-affiliate-catalog.js (InfoUzel.cz source of truth).
 * Regenerate when catalog titles change: node scripts/sync-premium-affiliate-catalog-titles.mjs
 */
export const PREMIUM_AFFILIATE_CATEGORY_TITLES_CS: Readonly<Record<string, string>> = {
  "aff-cestovni-kancelare": "Cestovní kanceláře",
  "aff-ubytovani-hotely": "Ubytování a hotely",
  "aff-letenky": "Doprava a cestování",
  "aff-letenky-letecka-doprava": "Letenky a letecká doprava",
  "aff-cestovni-pojisteni": "Cestovní pojištění",
  "aff-auto-moto": "Auto a moto",
  "aff-pneu-pneuservis": "Pneu a pneuservis",
  "aff-pojisteni": "Pojištění",
  "aff-finance": "Finance",
  "aff-energie-uspor": "Energie a úspory",
  "aff-lekarny": "Lékárny",
  "aff-zdravi-doplnky": "Zdraví a doplňky",
  "aff-kosmetika": "Kosmetika a parfémy",
  "aff-drogerie": "Drogerie",
  "aff-moda": "Móda a doplňky",
  "aff-boty": "Boty a tenisky",
  "aff-deti-hracky": "Děti a hračky",
  "aff-sportovni-obleceni": "Sportovní oblečení",
  "aff-sport-outdoor": "Sport a outdoor",
  "aff-dum-zahrada": "Dům a zahrada",
  "aff-nabytek": "Bydlení a vybavení",
  "aff-kuchyn": "Kuchyně a domácnost",
  "aff-elektro": "Elektro a chytrá domácnost",
  "aff-mobily": "Mobily a příslušenství",
  "aff-software": "Software a bezpečnost",
  "aff-knihy": "Knihy, hudba a hry",
  "aff-jidlo": "Jídlo a potraviny",
  "aff-zvirata": "Zvířata a chovatelství",
  "aff-kvetiny-darky": "Květiny a dárky",
  "aff-sperky-hodinky": "Šperky a hodinky",
  "aff-tv-streamovani": "TV a streamování",
  "aff-dilna-naradi": "Dílna a nářadí",
  "aff-inzerce-bazary": "Inzerce a bazary",
  "aff-realitni-kancelare": "Realitní kanceláře",
  "aff-reality-nemovitosti": "Reality a nemovitosti",
  "aff-kancelarske-potreby": "Kancelářské potřeby a vybavení",
};
