/**
 * Krajská + okresní sídla (veřejné administrativní údaje).
 * Slouží jen k sestavení mapové allowlist vrstvy — typeahead dataset zůstává plný.
 */
export const CZ_KRAJSKE_SIDLA = [
  "Praha",
  "Brno",
  "České Budějovice",
  "Jihlava",
  "Hradec Králové",
  "Karlovy Vary",
  "Liberec",
  "Olomouc",
  "Ostrava",
  "Pardubice",
  "Plzeň",
  "Ústí nad Labem",
  "Zlín",
  "Kutná Hora",
];

/** Sídla okresů (aktuální ČR) — doplněno o chybějící oproti kontrole seznamu */
export const CZ_OKRESNI_MESTA = [
  "Benešov",
  "Beroun",
  "Blansko",
  "Brno",
  "Bruntál",
  "Břeclav",
  "Česká Lípa",
  "České Budějovice",
  "Český Krumlov",
  "Cheb",
  "Chomutov",
  "Chrudim",
  "Děčín",
  "Domažlice",
  "Frýdek-Místek",
  "Havlíčkův Brod",
  "Hodonín",
  "Hradec Králové",
  "Jablonec nad Nisou",
  "Jeseník",
  "Jičín",
  "Jihlava",
  "Jindřichův Hradec",
  "Karlovy Vary",
  "Karviná",
  "Kladno",
  "Klatovy",
  "Kolín",
  "Kroměříž",
  "Kutná Hora",
  "Liberec",
  "Litoměřice",
  "Louny",
  "Mělník",
  "Mladá Boleslav",
  "Most",
  "Náchod",
  "Nový Jičín",
  "Nymburk",
  "Olomouc",
  "Opava",
  "Ostrava",
  "Pardubice",
  "Pelhřimov",
  "Plzeň",
  "Písek",
  "Prachatice",
  "Prostějov",
  "Přerov",
  "Příbram",
  "Rakovník",
  "Rokycany",
  "Rychnov nad Kněžnou",
  "Semily",
  "Sokolov",
  "Strakonice",
  "Sušice",
  "Svitavy",
  "Šumperk",
  "Tábor",
  "Tachov",
  "Teplice",
  "Trutnov",
  "Třebíč",
  "Uherské Hradiště",
  "Ústí nad Labem",
  "Ústí nad Orlicí",
  "Vsetín",
  "Vyškov",
  "Zlín",
  "Znojmo",
  "Žďár nad Sázavou",
];
